### ISSUE TITLE
Hamming distance

### ISSUE THREAD

**Issue by pjebs** [Ghirensics/ghiro#16]
@jekil  Could this be relevant:
https://github.com/jenssegers/imagehash

**Comment by iamjoshuamabina** [comment]
> @jekil Could this be relevant: https://github.com/jenssegers/imagehash

@pjebs I think it is: [Techniques &dash; Perceptual Hash](https://ghiro.readthedocs.io/en/latest/techniques/index.html#perceptual-hash)

**Comment by jekil** [comment]
@pjebs it is what @iamjoshuamabina linked.
So i am closing this, feel free to reopen it if I misunderstood.
